### ISSUE TITLE
Which imgui version is the current release of concur using?

### ISSUE THREAD

**Issue by chwba** [potocpav/python-concur#25]
If I print `imgui.__version__` I get 1.3.6, is this correct?

**Comment by potocpav** [comment]
Yes, it is. I created a fork of "pyimgui", because the upstream repository didn't contain the things I needed. More details as to why are in the README here:

https://github.com/potocpav/pyimgui

Functionally, it shouldn't differ much from upstream, and I am usind upstream docs all the time as a reference.

As for the C++ ImGui library, I am using the commit e9053515 from August, some time after the 1.78 release. This can be seen in the submodule "imgui-cpp" in the PyImGui fork. This could be easily upgraded if needed.

**Comment by chwba** [comment]
Well my personal opinion is to always try to stay as up to date as possible, updates mostly contain improvements, what do you think?

**Comment by chwba** [comment]
Id sure also like to contribute but I lack some understanding regarding how to implement c-bindings in python, so if you have some spare time and feel like schooling me for this one for an hour or two hmu :)

**Comment by potocpav** [comment]
Yes, sure, I like to stay up to date. It is mostly simple to upgrade ImGui, someone just has to periodically do that :) Do you want me to upgrade now? Or do you have any ideas on how to improve the process of upgrading? Now it is I think mostly:

1) Upgrade ImGui submodule
2) Run tests
3) Bump version an publish to PyPI

**Comment by chwba** [comment]
Id sure be willing to help out here, as I said I just need a short introduction on how to work with c-extensions/bindings in python. When you find some time Id propose we do a 1-2 hour session, where you just roughly show me how its done in practise, im sure this will suffice.

Yeah, please do, ill test it with my app and double check everything still works as intended.

**Comment by potocpav** [comment]
I upgraded PyImGui to the latest Docking ImGui (v1.3.9). Could you check whether everything works OK?

In the future, if you want another upgrade, please file an issue.

**Comment by chwba** [comment]
As of now, it seems all good, leave it open, ill do more tests later/tomorrow.

**Comment by chwba** [comment]
It seems to work perfectly fine.
